def testes(healthPlanet):
    print("------------------------------------------------- TESTE 1 -------------------------------------------------")
    print("DFS -> " + str(healthPlanet.grafo.procura_DFS("Arcozelo, Rua Doutor José Júlio Vieira Ramos", "Arcozelo, Rua Elias Garcia", print_visited = True)) + "\n")
    print("IDDFS -> " + str(healthPlanet.grafo.procura_IDDFS("Arcozelo, Rua Doutor José Júlio Vieira Ramos", "Arcozelo, Rua Elias Garcia", 20, print_visited = True)) + "\n")
    print("BFS -> " + str(healthPlanet.grafo.procura_BFS("Arcozelo, Rua Doutor José Júlio Vieira Ramos", "Arcozelo, Rua Elias Garcia", print_visited = True)) + "\n")
    print("UCS -> " + str(healthPlanet.grafo.procura_UCS("Arcozelo, Rua Doutor José Júlio Vieira Ramos", "Arcozelo, Rua Elias Garcia", print_visited = True)) + "\n")
    print("Dijkstra -> " + str(healthPlanet.grafo.procura_dijkstra("Arcozelo, Rua Doutor José Júlio Vieira Ramos", "Arcozelo, Rua Elias Garcia", print_visited = True)) + "\n")
    print("Bellman Ford -> "+ str(healthPlanet.grafo.procura_bellman_ford("Arcozelo, Rua Doutor José Júlio Vieira Ramos", "Arcozelo, Rua Elias Garcia", print_visited = True)) + "\n")
    print("Floyd Warshall -> "+ str(healthPlanet.grafo.procura_floyd_warshall("Arcozelo, Rua Doutor José Júlio Vieira Ramos", "Arcozelo, Rua Elias Garcia", print_visited = True)) + "\n")
    print("Random Walk -> "+ str(healthPlanet.grafo.random_walk("Arcozelo, Rua Doutor José Júlio Vieira Ramos", "Arcozelo, Rua Elias Garcia", print_visited = True)) + "\n")
    print("A* -> " + str(healthPlanet.grafo.procura_aStar("Arcozelo, Rua Doutor José Júlio Vieira Ramos", "Arcozelo, Rua Elias Garcia", print_visited = True)) + "\n")
    print("IDA* -> " + str(healthPlanet.grafo.procura_IDAstar("Arcozelo, Rua Doutor José Júlio Vieira Ramos", "Arcozelo, Rua Elias Garcia", print_visited = True)) + "\n")
    print("Greedy -> " + str(healthPlanet.grafo.procuraGreedy("Arcozelo, Rua Doutor José Júlio Vieira Ramos", "Arcozelo, Rua Elias Garcia", print_visited = True)) + "\n")

    print("------------------------------------------------- TESTE 2 -------------------------------------------------")
    print("\n" + "DFS -> " + str(healthPlanet.grafo.procura_DFS("Barcelos, Avenida Dom Nuno Álvares Pereira", "Arcozelo, Rua Elias Garcia", print_visited = True)) + "\n")
    print("IDDFS -> " + str(healthPlanet.grafo.procura_IDDFS("Barcelos, Avenida Dom Nuno Álvares Pereira", "Arcozelo, Rua Elias Garcia", 20, print_visited = True)) + "\n")
    print("BFS -> " + str(healthPlanet.grafo.procura_BFS("Barcelos, Avenida Dom Nuno Álvares Pereira", "Arcozelo, Rua Elias Garcia", print_visited = True)) + "\n")
    print("UCS -> " + str(healthPlanet.grafo.procura_UCS("Barcelos, Avenida Dom Nuno Álvares Pereira", "Arcozelo, Rua Elias Garcia", print_visited = True)) + "\n")
    print("Dijkstra -> " + str(healthPlanet.grafo.procura_dijkstra("Barcelos, Avenida Dom Nuno Álvares Pereira", "Arcozelo, Rua Elias Garcia", print_visited = True)) + "\n")
    print("Bellman Ford -> "+ str(healthPlanet.grafo.procura_bellman_ford("Barcelos, Avenida Dom Nuno Álvares Pereira", "Arcozelo, Rua Elias Garcia", print_visited = True)) + "\n")
    print("Floyd Warshall -> "+ str(healthPlanet.grafo.procura_floyd_warshall("Barcelos, Avenida Dom Nuno Álvares Pereira", "Arcozelo, Rua Elias Garcia", print_visited = True)) + "\n")
    print("Random Walk -> "+ str(healthPlanet.grafo.random_walk("Barcelos, Avenida Dom Nuno Álvares Pereira", "Arcozelo, Rua Elias Garcia", print_visited = True)) + "\n")
    print("A* -> " + str(healthPlanet.grafo.procura_aStar("Barcelos, Avenida Dom Nuno Álvares Pereira", "Arcozelo, Rua Elias Garcia", print_visited = True)) + "\n")
    print("IDA* -> " + str(healthPlanet.grafo.procura_IDAstar("Barcelos, Avenida Dom Nuno Álvares Pereira", "Arcozelo, Rua Elias Garcia", print_visited = True)) + "\n")
    print("Greedy -> " + str(healthPlanet.grafo.procuraGreedy("Barcelos, Avenida Dom Nuno Álvares Pereira", "Arcozelo, Rua Elias Garcia", print_visited = True)) + "\n")

    print("------------------------------------------------- TESTE 3 -------------------------------------------------")
    print("\n" + "DFS -> " + str(healthPlanet.grafo.procura_DFS("Arcozelo, Avenida João Duarte", "Barcelos, Largo dos Capuchinhos", print_visited = True)) + "\n")
    print("IDDFS -> " + str(healthPlanet.grafo.procura_IDDFS("Arcozelo, Avenida João Duarte", "Barcelos, Largo dos Capuchinhos", 20, print_visited = True)) + "\n")
    print("BFS -> " + str(healthPlanet.grafo.procura_BFS("Arcozelo, Avenida João Duarte", "Barcelos, Largo dos Capuchinhos", print_visited = True)) + "\n")
    print("UCS -> " + str(healthPlanet.grafo.procura_UCS("Arcozelo, Avenida João Duarte", "Barcelos, Largo dos Capuchinhos", print_visited = True)) + "\n")
    print("Dijkstra -> " + str(healthPlanet.grafo.procura_dijkstra("Arcozelo, Avenida João Duarte", "Barcelos, Largo dos Capuchinhos", print_visited = True)) + "\n")
    print("Bellman Ford -> "+ str(healthPlanet.grafo.procura_bellman_ford("Arcozelo, Avenida João Duarte", "Barcelos, Largo dos Capuchinhos", print_visited = True)) + "\n")
    print("Floyd Warshall -> "+ str(healthPlanet.grafo.procura_floyd_warshall("Arcozelo, Avenida João Duarte", "Barcelos, Largo dos Capuchinhos", print_visited = True)) + "\n")
    print("Random Walk -> "+ str(healthPlanet.grafo.random_walk("Arcozelo, Avenida João Duarte", "Barcelos, Largo dos Capuchinhos", print_visited = True)) + "\n")
    print("A* -> " + str(healthPlanet.grafo.procura_aStar("Arcozelo, Avenida João Duarte", "Barcelos, Largo dos Capuchinhos", print_visited = True)) + "\n")
    print("IDA* -> " + str(healthPlanet.grafo.procura_IDAstar("Arcozelo, Avenida João Duarte", "Barcelos, Largo dos Capuchinhos", print_visited = True)) + "\n")
    print("Greedy -> " + str(healthPlanet.grafo.procuraGreedy("Arcozelo, Avenida João Duarte", "Barcelos, Largo dos Capuchinhos", print_visited = True)) + "\n")